version: '3.7'

services:
  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    # volumes: 
    #   - ./database/:/var/lib/mysql:rw
    ports: 
      - 3306:3306
    environment:
      - DATABASE_USER=root
      #- MYSQL_USER=root
      #- MYSQL_PASSWORD=root
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=webfoot_db

  adminer:
    image: adminer
    restart: always
    depends_on:
      - mysql
    ports:
      - 8080:8080
  
  webfoot:
    restart: always
    depends_on:
      - mysql
    volumes: 
      - .:/webfoot/
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
      - PYTHONUNBUFFERED=1
    command: python manage.py runserver 0.0.0.0:8000
